### ISSUE TITLE
yellowdig access

### ISSUE THREAD

**Issue by afullerton** [DS4PS/cpp-526-sum-2020#30]
Hi, when I click on the link to YellowDig (from the course schedule), it directs me to an access denied page on canvas. 

Let me know if there is anything I need to do on my end and thanks for your help.

**Comment by krittschof** [comment]
Hi, I am having the same issues as afullerton. I went through the information prior to moving forward on my introduction. 
Thanks, Kerri

**Comment by lecy** [comment]
There was a link using an old format - should be fixed, please try now!

**Comment by afullerton** [comment]
I'm still having the same issue, this is the link I have:

https://canvas.asu.edu/courses/54986/assignments/1306428

Thanks,
Allegra

**Comment by lecy** [comment]
@afullerton try refreshing your browser (the site takes a minute to update)

**Comment by lecy** [comment]
It was sending you to the summer section, not fall. This is the correct link: https://canvas.asu.edu/courses/67636/assignments/1615950

Also note that this is the discussion board for summer. I think you used the link from the syllabus (I found another laggard)? If you are bookmarking links, use this one (Fall 2020 section), or use the "Get Help" link on the menu bar:

https://ds4ps.org/cpp-526-fall-2020/help/

**Comment by afullerton** [comment]
I found the right link, thank you. 

Yes, this was the link from the syllabus too. I'll update bookmarks on my end.  --Allegra

**Comment by lecy** [comment]
Excellent. 

We switched up the format for links so they don't have to be manually updated at the start of each term, but there were over 400 links so we may have missed a few!

Any flags of broken links are appreciated.
